enum ErrorCode {
    SERVICE_Closed = 403000,
    SERVICE_PROVIDER_ApiError = 400001,
    NOT_FOUND_User = 404100,
    NOT_FOUND_Role,
    NOT_FOUND_VerificationCode,
    NOT_FOUND_RefreshToken,
    NOT_FOUND_PlanningSession,
    NOT_FOUND_Wallet,
    NOT_FOUND_WalletAddress,
    NOT_FOUND_WalletValidator,
    NOT_FOUND_NewsletterSubscription,
    NOT_FOUND_Application,
    NOT_FOUND_ApplicationScope,
    NOT_FOUND_DiscordAccount,
    NOT_FOUND_DiscordValidator,
    NOT_FOUND_ApplicationUser,
    NOT_FOUND_Log,
    CONFLICT_Email = 409200,
    CONFLICT_PlanningSession,
    CONFLICT_WalletAddress,
    CONFLICT_WalletBind,
    CONFLICT_SameEmail,
    CONFLICT_DiscordBind,
    CONFLICT_DiscordNotAvailable,
    REJECTED_Password = 400300,
    REJECTED_VerificationCode,
    REJECTED_Signature,
    REJECTED_WalletUnbind,
    REQUIRE_Token = 403400,
    REQUIRE_Role,
    REQUIRE_Whitelist,
    REQUIRE_Access,
    REQUIRE_Ownership,
    REQUIRE_APP_Scope,
    REQUIRE_APP_TypeAccess,
    REQUIRE_APP_AccessRequire,
    REQUIRE_DiscordEmail,
    REQUIRE_ApiKey,
    INVALID_VerificationCode = 400500,
    INVALID_Token,
    INVALID_Parameter,
    INVALID_ApiKey,
    EXPIRED_VerificationCode = 400600,
    EXPIRED_Token,
    MISSING_Parameter = 404700,
    MISSING_Filter,
    RESTRICTED_VerificationCode = 403800,
    RESTRICTED_Login
}

export default ErrorCode