name: Production CI & CD

on:
  push:
    branches: [main]

jobs:
  build:
    name: ci-prod
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test

  deploy:
    name: cd-prod
    needs: build
    environment: secrets
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PRIVATE_PASSPHRASE }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/dlab/apps/dlab-sso
            git pull origin main
            npm ci
            echo "" > .env
            echo "PORT=${{ secrets.APP_PORT }}" >> .env
            echo "LOCALHOST=false" >> .env
            echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> .env
            echo "MYSQL_DB_NAME=${{ secrets.MYSQL_DB_NAME }}" >> .env
            echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
            echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
            echo "MYSQL_PORT=${{ secrets.MYSQL_PORT }}" >> .env
            echo "MAIL_KEY=${{ secrets.APP_MAIL_KEY }}" >> .env
            echo "MAIL_FROM=${{ secrets.APP_MAIL_FROM }}" >> .env
            echo "MAIL_FROM_NAME=${{ secrets.APP_MAIL_FROM_NAME }}" >> .env
            echo "COOKIE_KEY=${{ secrets.APP_COOKIE_KEY }}" >> .env
            echo "COOKIE_DOMAIN=${{ secrets.APP_COOKIE_DOMAIN }}" >> .env
            echo "JWT_SECRET=${{ secrets.APP_JWT_SECRET }}" >> .env
            echo "JWT_REFRESH_SECRET=${{ secrets.APP_JWT_REFRESH_SECRET }}" >> .env
            echo "AXE_SHOW_META=false" >> .env
            pm2 start npm --name "dlab-sso" -- start